### ISSUE TITLE
Update Package To Use New autocomplete-plus API

### ISSUE THREAD

**Issue by joefitzgerald** [lukehoban/atom-ide-flow#11]
Please:

* Switch to the new `autocomplete-plus` `1.0.0` API: https://github.com/atom-community/autocomplete-plus/wiki/Provider-API
* Move away from having 1 provider instance for every editor instance

**Comment by joefitzgerald** [comment]
The old API will be removed on Tuesday, February 10th, 2015. Please update to use the new API, or let me know if you have issues with that timeline.

**Comment by LeonFedotov** [comment]
@lukehoban Hi man, what do you think, will you be able to do this?

**Comment by lukehoban** [comment]
Thanks @unknownexception for the update!
