### ISSUE TITLE
Follow up on prevention of normal symbol completion

### ISSUE THREAD

**Issue by murphyrandle** [lukehoban/atom-ide-flow#31]
Following up on: https://github.com/lukehoban/atom-ide-flow/issues/24

Just a note here, I've upgraded both autocomplete+ and flow-ide, and now my normal symbol completion is gone again whenever I have flow-ide activated.

I haven't dug into what's causing it yet, but I'll let you know if I find anything.

**Comment by lukehoban** [comment]
This should be fixed with 81595ef05291d56d53e37b44f7aa431b863a07ba.
