### ISSUE TITLE
Deprecated Atom APIs will be removed June 1st

### ISSUE THREAD

**Issue by benogle** [lukehoban/atom-ide-flow#37]
Atom will no longer load this package after June 1st without changes. There are a couple deprecations on the latest version (`0.7.0`) of this package:

1. atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use `atom.views.getView(atom.workspace)`, which returns an HTMLElement.
1. Use ::dispose to cancel subscriptions instead of ::off
1. Call ::getActiveTextEditor instead

Visit https://gist.github.com/benogle/6d09e295c84b717ef9b4 and search for your package name to see up-to-date deprecations.

If this package has been replaced by another package or functionality in core, please reply with this information.

See https://github.com/atom/atom/issues/6867 for more info. Thanks!

**Comment by lukehoban** [comment]
Thanks for the heads up, I wasn't seeing these reported in the deprecations window in Atom.  They should be fixed in v0.8.0 of the package with a36b3a1286986ac86da683c97d1974e87d42e666.
